apiVersion: apps/v1
kind: Deployment
metadata:
  name: lookup-deployment
  labels:
    app: lookup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lookup
  template:
    metadata:
      labels:
        app: lookup
    spec:
      containers:
      - name: lookup
        image: lookup:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 3

